services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
  db:
    image: postgres:12.1
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
  bundle:
